name: GPAuctions
author: RoboMWM
version: ${project.version} commit ${git.commit.id.abbrev}
main: com.robomwm.gpauctions.GPAuctions
depend: [GriefPrevention, Vault]
softdepend: [GPRealEstate]
api-version: '1.13'
commands:
  gpauctions:
    usage: /gpauctions
  gpacancel:
    usage: /gpacancel - Cancels an auction. Stand in the claim where the auction is occurring.
